name: Atualizar Mapa SPPO

on:
  schedule:
    - cron: '*/30 * * * *' # O robô vai rodar a cada 30 minutos
  workflow_dispatch:      # Permite que você clique em um botão para atualizar agora

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que o robô salve o index.html no seu repositório
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Executar Gerador de Mapa
        run: python main.py

      - name: Salvar e Subir o Mapa Novo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "Mapa atualizado automaticamente: $(date)" || echo "Sem mudanças para salvar"
          git push